//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int PKId_detallecompra { get; set; }
        public int FKNum_compra { get; set; }
        public int FKProducto1 { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
