//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int PKId_detalle { get; set; }
        public int FKNum_venta { get; set; }
        public int FKProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Venta Venta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
