//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public int FKIdEmpleado1 { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
